"""
ComfyUI-VideoDescription
Video description and storyboard custom nodes for ComfyUI
"""

from .video_nodes import (
    NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .storyboard_nodes import (
    NODE_CLASS_MAPPINGS as STORYBOARD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS,
)

# Merge node mappings
NODE_CLASS_MAPPINGS = {
    **VIDEO_NODE_CLASS_MAPPINGS,
    **STORYBOARD_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **STORYBOARD_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
