[project]
name = "videodescription"
description = "Video description custom nodes for ComfyUI powered by advanced vision-language models."
version = "1.0.0"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]

dependencies = ["# ============================================================", "# ComfyUI-VideoDescription Dependencies", "# ============================================================", "# IMPORTANT: Install ONLY the packages ComfyUI doesn't already have", "# ComfyUI already provides: torch, transformers, pillow, numpy", "#", "# Installation command:", "#   pip install qwen-vl-utils opencv-python", "#", "# For DAM support (CUDA only):", "#   pip install git+https://github.com/NVlabs/describe-anything.git", "# ============================================================", "# Required for Qwen3-VL node", "qwen-vl-utils", "# Required for video processing (if not already installed)", "opencv-python", "# Optional: NVIDIA DAM-3B-Video support (CUDA ONLY)", "# Uncomment ONLY if you have NVIDIA GPU and want DAM region analysis:", "# git+https://github.com/NVlabs/describe-anything.git", "# Optional: 4-bit quantization support (reduces VRAM usage)", "# Uncomment if you want to use use_4bit=True option:", "# bitsandbytes", "# ============================================================", "# Dependencies that ComfyUI should already provide:", "# ============================================================", "# DO NOT INSTALL THESE - they will conflict with ComfyUI:", "# - torch (ComfyUI manages this)", "# - transformers (ComfyUI manages this)", "# - accelerate (ComfyUI manages this)", "# - pillow (ComfyUI manages this)", "# - numpy (ComfyUI manages this)", "# ============================================================"]

[project.urls]
Repository = "https://github.com/IXIWORKS-KIMJUNGHO/ComfyUI-VideoDescription"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/IXIWORKS-KIMJUNGHO/ComfyUI-VideoDescription/wiki"
"Bug Tracker" = "https://github.com/IXIWORKS-KIMJUNGHO/ComfyUI-VideoDescription/issues"

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-VideoDescription"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

